/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import CRUD.NhanVienCRUD;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Date;
import java.util.List;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.NhanVien;

/**
 *
 * @author dell
 */
public class frmPhanQuyen extends javax.swing.JFrame {
    private NhanVienCRUD nhanVienCRUD;
    private List<NhanVien> nhanVienQuanly;
    private List<NhanVien> nhanVienBanHang
            ;
    /**
     * Creates new form frmPhanQuyen
     */
    public frmPhanQuyen() {
        initComponents();
        nhanVienCRUD = new NhanVienCRUD();
        LoadNhanVienBanHang();
        LoadNhanVienQuanLy();
        renderTable();
    }
    
    private void renderTable(){
        ButtonColumn buttonThemQuyen;
        ButtonColumn buttonXoaQuyen;
        tbNhanVienBanHang.setRowSelectionAllowed(false);
        tbNhanVienQuanLy.setRowSelectionAllowed(false);
        themQuyenQuanLy();
        xoaQuyenQuanLy();
        tbNhanVienBanHang.setRowHeight(40);
        tbNhanVienQuanLy.setRowHeight(40);
        Icon upIcon = new  ImageIcon("C:\\HUTECH\\New\\Mang may tinh\\Giua ky\\VanPhongPhamBaToCom\\src\\icons\\up.png");
        Icon downIcon = new  ImageIcon("C:\\HUTECH\\New\\Mang may tinh\\Giua ky\\VanPhongPhamBaToCom\\src\\icons\\down.png");
        buttonThemQuyen = new ButtonColumn(tbNhanVienBanHang, tbNhanVienBanHang.getColumnCount() - 1,upIcon);
        buttonXoaQuyen = new ButtonColumn(tbNhanVienQuanLy, tbNhanVienQuanLy.getColumnCount() - 1,downIcon);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbNhanVienBanHang = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbNhanVienQuanLy = new javax.swing.JTable();
        btnTroVe = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Nhân viên bán hàng");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Nhân viên quản lý");

        tbNhanVienBanHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã NV", "Tên nhân viên", "Số điện thoại", "Địa chỉ", "Ngày sinh", "Giới tính", "CMND", "Thêm quyền quản lý"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tbNhanVienBanHang);

        tbNhanVienQuanLy.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã NV", "Tên nhân viên", "Số điện thoại", "Địa chỉ", "Ngày sinh", "Giới tính", "CMND", "Xoá quyền quản lý"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tbNhanVienQuanLy);

        btnTroVe.setText("Trở về");
        btnTroVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTroVeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 954, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(btnTroVe)
                        .addGap(133, 133, 133)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 954, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(btnTroVe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 234, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(68, 68, 68)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(306, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTroVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTroVeActionPerformed
        // TODO add your handling code here:
        frmQuanLyNhanVien open = new frmQuanLyNhanVien();
        open.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnTroVeActionPerformed

    private void LoadNhanVienBanHang(){
        nhanVienBanHang = nhanVienCRUD.getNhanVienBanHang();       
        DefaultTableModel model = (DefaultTableModel) tbNhanVienBanHang.getModel();
        model.setRowCount(0); 
        for (NhanVien nhanVien : nhanVienBanHang) {
            String maNV = nhanVien.getMaNV();
            String tenNV = nhanVien.getTenNV();
            String diaChi = nhanVien.getDiaChi();
            String sdt = nhanVien.getSdt();
            String gioiTinh = nhanVien.getGioiTinh();
            Date ngaySinh = nhanVien.getNgaySinh();
            String cmndCCCD = nhanVien.getCMND_CCCD();
            model.addRow(new Object[]{maNV, tenNV,sdt, diaChi,ngaySinh,  gioiTinh , cmndCCCD});
        }
    }
    
    private void LoadNhanVienQuanLy(){
        nhanVienQuanly = nhanVienCRUD.getNhanVienQuanLy();       
        DefaultTableModel model = (DefaultTableModel) tbNhanVienQuanLy.getModel();
        model.setRowCount(0); 
        for (NhanVien nhanVien : nhanVienQuanly) {
            String maNV = nhanVien.getMaNV();
            String tenNV = nhanVien.getTenNV();
            String diaChi = nhanVien.getDiaChi();
            String sdt = nhanVien.getSdt();
            String gioiTinh = nhanVien.getGioiTinh();
            Date ngaySinh = nhanVien.getNgaySinh();
            String cmndCCCD = nhanVien.getCMND_CCCD();
            model.addRow(new Object[]{maNV, tenNV,sdt, diaChi,ngaySinh,  gioiTinh , cmndCCCD});
        }
    }
    
    private void themQuyenQuanLy(){
        // Add a MouseListener to the table
        tbNhanVienBanHang.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int row = tbNhanVienBanHang.rowAtPoint(e.getPoint());
                int column = tbNhanVienBanHang.columnAtPoint(e.getPoint());
                if (column == tbNhanVienBanHang.getColumnCount() - 1) {
                    
                    int selectedRow = tbNhanVienBanHang.convertRowIndexToModel(row);
                    Object idNhanVien = tbNhanVienBanHang.getModel().getValueAt(selectedRow, 0);
                    int result = JOptionPane.showConfirmDialog(
                            null,
                            "Bạn có chắc muốn thêm quyền quản lý nhân viên này? ",
                            "Xác nhận",
                            JOptionPane.YES_NO_OPTION);

                    if (result == JOptionPane.YES_OPTION)
                    {
                            if(nhanVienCRUD.themQuyenQuanLy(idNhanVien.toString())){
                                JOptionPane.showMessageDialog(null, "Thêm quyền quản lý thành công");
                                LoadNhanVienBanHang();
                                LoadNhanVienQuanLy();
                            }
                            
                    }
                     else
                        return;
                }

            }
        });
    }
    
    private void xoaQuyenQuanLy(){
        // Add a MouseListener to the table
        tbNhanVienQuanLy.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int row = tbNhanVienQuanLy.rowAtPoint(e.getPoint());
                int column = tbNhanVienQuanLy.columnAtPoint(e.getPoint());
                if (column == tbNhanVienQuanLy.getColumnCount() - 1) {
                    
                    int selectedRow = tbNhanVienQuanLy.convertRowIndexToModel(row);
                    Object idNhanVien = tbNhanVienQuanLy.getModel().getValueAt(selectedRow, 0);
                    int result = JOptionPane.showConfirmDialog(
                            null,
                            "Bạn có chắc muốn xoá quyền quản lý của nhân viên này? ",
                            "Xác nhận",
                            JOptionPane.YES_NO_OPTION);

                    if (result == JOptionPane.YES_OPTION)
                    {
                            if(nhanVienCRUD.xoaQuyenQuanLy(idNhanVien.toString())){
                                JOptionPane.showMessageDialog(null, "Xoá quyền quản lý thành công");
                                LoadNhanVienBanHang();
                                LoadNhanVienQuanLy();
                            }
                            
                    }
                    else
                        return;
                
                }

            }
        });
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPhanQuyen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPhanQuyen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPhanQuyen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPhanQuyen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPhanQuyen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTroVe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tbNhanVienBanHang;
    private javax.swing.JTable tbNhanVienQuanLy;
    // End of variables declaration//GEN-END:variables
}
